name: Run checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/flake-checker-action@main"
        with:
          fail-mode: true
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/flakehub-cache-action@main"
      - name: Flake check
        run: nix develop --command check
      - name: Check formatting
        run: |
          nix develop --command nixpkgs-fmt --check $(git ls-files '*.nix')
